#! /usr/bin/bash
set -e

mkdir build-scripts
cd build-scripts

cmake $RECIPE_DIR/scripts
cd ..

# Bundled config.sub/config.guess predate aarch64 triplets -- replace with
# the current ones from the gnuconfig package before configuring.
for f in config.sub config.guess; do
  find . -name "$f" -exec cp "$BUILD_PREFIX/share/gnuconfig/$f" {} \;
done

# Regenerate configure/Makefile.in with conda's own autotools rather than
# using LHAPDF's pre-shipped configure script (generated by upstream's own,
# non-conda autotools) -- conda-forge's own lhapdf-feedstock does the same.
autoreconf --install --force

./configure --prefix=$PREFIX FCFLAGS="${FFLAGS} -std=legacy" CXXFLAGS="${CXXFLAGS}"

NPROC=$(nproc 2>/dev/null || sysctl -n hw.ncpu)
make -j$NPROC
make install
