#! /usr/bin/bash
set -e

mkdir build-scripts
cd build-scripts

cmake $RECIPE_DIR/scripts
cd ..

# Bundled config.sub/config.guess predate aarch64 triplets -- replace with
# the current ones from the gnuconfig package before configuring.
for f in config.sub config.guess; do
  find . -name "$f" -exec cp "$BUILD_PREFIX/share/gnuconfig/$f" {} \;
done

# Upstream's own bin/lhapdf-config.in has a typo: its help text advertises
# --incdir, but the case statement only matches --includedir. Several
# downstream consumers (apfel, mcfm, ...) call `lhapdf-config --incdir`
# per the documented interface and break on this -- accept both.
sed -i 's/--includedir)   show_incdir=1 ;;/--includedir|--incdir) show_incdir=1 ;;/' bin/lhapdf-config.in

# Regenerate configure/Makefile.in with conda's own autotools rather than
# using LHAPDF's pre-shipped configure script (generated by upstream's own,
# non-conda autotools) -- conda-forge's own lhapdf-feedstock does the same.
autoreconf --install --force

# libtool's C++ runtime-linkage check (regenerated by autoreconf above)
# explicitly probes for -lstdc++ using the plain C driver rather than
# g++, which doesn't carry g++'s own default libstdc++ search path --
# fails with "ld: library not found for -lstdc++" on macOS where
# Apple's ld64 (not GNU ld) is doing the linking. Point it at conda's
# own compiler-provided lib dir explicitly.
export LDFLAGS="${LDFLAGS} -L${BUILD_PREFIX}/lib"

./configure --prefix=$PREFIX FCFLAGS="${FFLAGS} -std=legacy" CXXFLAGS="${CXXFLAGS}"

NPROC=$(nproc 2>/dev/null || sysctl -n hw.ncpu)
make -j$NPROC
make install
