#! /usr/bin/bash
set -e

mkdir build-scripts
cd build-scripts

cmake $RECIPE_DIR/scripts
cd ..

# Bundled config.sub/config.guess predate aarch64 triplets -- replace with
# the current ones from the gnuconfig package before configuring.
for f in config.sub config.guess; do
  find . -name "$f" -exec cp "$BUILD_PREFIX/share/gnuconfig/$f" {} \;
done

# Regenerate configure/Makefile.in with conda's own autotools rather than
# using LHAPDF's pre-shipped configure script (generated by upstream's own,
# non-conda autotools) -- conda-forge's own lhapdf-feedstock does the same.
autoreconf --install --force

# Belt-and-suspenders: even with the pin above, whatever sysroot_linux-64
# actually gets solved for this environment (can be forced newer than our
# own c_stdlib_version preference by an unrelated dependency's own
# requirement, e.g. python/cython) determines which glibc headers get
# used. -std=gnu17 caps __STDC_VERSION__ so glibc's C23 strtol/atoi
# redirect (__isoc23_strtol, a GLIBC_2.38 symbol) can't trigger regardless
# of which sysroot wins the solve.
./configure --prefix=$PREFIX FCFLAGS="${FFLAGS} -std=legacy" CFLAGS="${CFLAGS} -std=gnu17" CXXFLAGS="${CXXFLAGS} -std=gnu++17"

NPROC=$(nproc 2>/dev/null || sysctl -n hw.ncpu)
make -j$NPROC
make install
