package:
  name: {{ environ.get('ANACONDA_PACKAGE')|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION')|string|replace('-', '.') }}

{% set version = environ.get('COMMIT_TAG', None) or environ.get('COMMIT_LATEST_TAG', None) or 0 %}
{% set sha256 = {
    "6.5.4": "2443a4b32cc3b0597c8248bd6e25703ace9c91a7a253c5f60b1b5428ef9c869e"
} %}

{% set version = version or sha256.keys()|first %}
source:
  url: "https://lhapdf.hepforge.org/downloads/?f=LHAPDF-{{ version }}.tar.gz"
  {% if sha256.get(version, None) %}
  sha256: {{ sha256.get(version) }}
  {% endif %}

requirements:
  build:
    - {{ compiler('gfortran') }}   # GNU Fortran compiler
    - {{ compiler('c') }}          # GNU C compiler
    - {{ compiler('cxx') }}        # GNU C++ compiler
    - cmake                        # Build system
    - make                         # Make utility
    - python<3.10

  host:
    - python<3.10
    - pip
    - setuptools

  run:
    - python<3.10

about:
  home: "https://lhapdf.hepforge.org"
  license: "GPL-3.0"
  summary: "LHAPDF is the standard tool for evaluating parton distribution functions (PDFs) in high-energy physics."
  description: |
    LHAPDF is the standard tool for evaluating parton distribution functions (PDFs) in high-energy physics. PDFs encode the flavour and momentum structure of composite particles, such as protons, pions and nuclei; most cross-section calculations are based on parton-level matrix-elements which must be connected to the real interacting particles, hence PDFs are an essential ingredient of phenomenological and experimental studies at hadron and heavy-ion colliders (e.g. LHC, HERA, Tevatron, EIC, FCC) and in cosmic-ray physics.

extra:
  recipe-maintainers:
    - meiyasan
