{% set versions = {
    "6.5.5": "641d5ea0942b79e4447e15e5a33491ff3c7032d71d618119935e14ad27f5e3a5",
    "5.9.1": "86b9b046d7f25627ce2aab6847ef1c5534972f4bae18de98225080cf5086919c"
} %}

{% set gnu_build_pin = " 14.*" %}
{% set gnu_host_pin   = " >=14" %}

{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "lhapdf")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

source:
  {% if version.startswith('5') %}
  url: "https://lhapdf.hepforge.org/downloads/?f=old/lhapdf-{{ version }}.tar.gz"
  {% else %}
  url: "https://lhapdf.hepforge.org/downloads/?f=LHAPDF-{{ version }}.tar.gz"
  {% endif %}
  {% if versions.get(version, None) %}
  sha256: {{ versions.get(version) }}
  {% endif %}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('gfortran') }}
    - python
    - cython >=0.24
    - gnuconfig
    - make
    - cmake
    - automake
    - autoconf
    - libtool
  host:
    - python
    - cython >=0.24
  run:
    - python

about:
  home: "https://lhapdf.hepforge.org"
  license: "GPL-3.0"
  summary: "LHAPDF is the standard tool for evaluating parton distribution functions (PDFs) in high-energy physics."
  description: |
    LHAPDF is the standard tool for evaluating parton distribution functions (PDFs) in high-energy physics. PDFs encode the flavour and momentum structure of composite particles, such as protons, pions and nuclei; most cross-section calculations are based on parton-level matrix-elements which must be connected to the real interacting particles, hence PDFs are an essential ingredient of phenomenological and experimental studies at hadron and heavy-ion colliders (e.g. LHC, HERA, Tevatron, EIC, FCC) and in cosmic-ray physics.

extra:
  recipe-maintainers:
    - meiyasan
